services:
  patients.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=patientsdb;Port=5432;Database=therabee_patients;Username=postgres;Password=secret
      - PortraitStorage__RootPath=/app/data/portraits
      - OpenAI__ApiKey=THERABEEKEY
    depends_on:
      - patientsdb
    ports:
      - "6001:8080"
    volumes:
      - portrait_images:/app/data/portraits

  patientsdb:
    container_name: therabee-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=therabee_patients
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_therabee:/var/lib/postgresql/data/
